version: "3"
services:
  web:
    container_name: ruby_demo_web
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "exec bin/rails -s -p 3000"
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
